#
# This script contains the instuctions generated by:
#     $(pyenv virtualenv-init -)
# So they can be inspected or partially executed.
# It doesn't need to be sourced if the above statement is eval'd in
# .zshenv/.bashrc/.bash_profile
#
# -------------------------------------------------------------------------------
# -------------------------------------------------------------------------------
# ,-------------------------,
# | pyenv virtualenv-init - |
# '-------------------------'
# enable auto-activation of virtualenvs
# otherwise, they can be manually activated with 'pyenv activate'

# add shims to front of $PATH
# export PATH="/home/troy/.pyenv/plugins/pyenv-virtualenv/shims:${PATH}";
pathprepend "/home/troy/.pyenv/plugins/pyenv-virtualenv/shims:${PATH}";

# set $PYENV-VIRTUALENV-INIT
export PYENV_VIRTUALENV_INIT=1;

if [[ -z $pyenv_virtualenv_noauto ]]; then
    _pyenv_virtualenv_hook() {
        local ret=$?
        if [ -n "$VIRTUAL_ENV" ]; then
            eval "$(pyenv sh-activate --quiet || pyenv sh-deactivate --quiet || true)" || true
        else
            eval "$(pyenv sh-activate --quiet || true)" || true
        fi
        return $ret
    };
fi
